files:
  include: src/**/*.scss
options:
  formatter: stylish
  merge-default-rules: false
rules:
  border-zero:
    - 2
    - convention: "0"
  brace-style:
    - 2
    - style: 'stroustrup'
  class-name-format:
    - 0
    - convention: hyphenatedlowercase
  empty-line-between-blocks:
    - 2
    - allow-single-line-rulesets: false
    - include: true
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline:
    - 2
    - include: true
  hex-length:
    - 2
    - style: short
  hex-notation:
    - 2
    - style: lowercase
  indentation:
    - 2
    - size: 2
  leading-zero:
    - 2
    - include: false
  no-color-keywords: 2
  no-color-literals:
    - 2
    - allow-rgba: true
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-qualifying-elements:
    - 2
    - allow-element-with-attribute: false
      allow-element-with-class: false
      allow-element-with-id: false
  no-trailing-zero: 2
  no-transition-all: 2
  no-url-protocols: 2
  no-vendor-prefixes:
    - 2
    - ignore-non-standard: true
  one-declaration-per-line: 2
  quotes:
    - 2
    - style: double
  shorthand-values: 2
  single-line-per-selector: 2
  space-after-bang:
    - 2
    - include: false
  space-after-colon:
    - 2
    - include: true
  space-after-comma: 2
  space-before-bang:
    - 2
    - include: true
  space-before-brace:
    - 2
    - include: true
  space-before-colon: 2
  space-between-parens:
    - 2
    - include: false
  trailing-semicolon: 2
  url-quotes: 2
  zero-unit: 2
